### ISSUE TITLE
error （hangfire.sqlserver update to 1.7.7）

### ISSUE THREAD

**Issue by yuzd** [face-it/Hangfire.Tags#10]
update to 1.7.7  error:
![image](https://user-images.githubusercontent.com/16083659/68009880-12bef100-fcbe-11e9-8a34-771a904a9add.png)

**Comment by KveRa** [comment]
Causing Errors in Hangfire 1.7.8.
Removing the UseTags() everithing works fine...

**Comment by yuzd** [comment]
any idea to fix it?

**Comment by yuzd** [comment]
@face-it could you publish new version to nuget?

**Comment by erwin-faceit** [comment]
I've just pushed a new version to Nuget. If you experience any other issues with this version, please open a new issue.

**Comment by yuzd** [comment]
thanks.
