### ISSUE TITLE
Support for Redis?

### ISSUE THREAD

**Issue by ewahner** [face-it/Hangfire.Tags#12]
This looks like a super-helpful extension.  Are you considering adding support for other providers?

**Comment by erwin-faceit** [comment]
I've just pushed an initial version for Redis support.

On a sidenote: if you're already using Hangfire.Tags, where Hangfire is using Redis as storage, the numbers will be wrong. The Redis implementation uses a custom filter to create different sets per tag and state, which is quite a big performance boost, but it also means that already existing jobs and their tags are not yet stored in those sets.
