### ISSUE TITLE
NullReference Exception on Job Creation

### ISSUE THREAD

**Issue by PaulARoy** [face-it/Hangfire.Tags#15]
Hi,
I've just updated the nuget package and I experience a nullreference exception on job creation.

This really seems to be the possible NRE you talk about in https://github.com/face-it/Hangfire.Tags/commit/fd5dc19b0b0184f3b5d497d7076f32109967bba2

- Could you provide an update to fix it?
- Is there a possibility to workaround this?

Best regards,

**Comment by yongliu-mdsol** [comment]
@PaulARoy 

We encountered similar issue from our testing. 
It seems to be the line below where BackgroundJob is null.
https://github.com/face-it/Hangfire.Tags/blob/master/src/Hangfire.Tags/States/CreateJobFilter.cs#L16

**Comment by erwin-faceit** [comment]
The change @yongliu-mdsol suggested is added to release 1.5.1. I'm not sure, however, that it will fix your problem. It will merely throw another exception.

Let me now how things works out. If you're still having problems, please supply a snippet of code of initialization and usage (including used tags).

**Comment by PaulARoy** [comment]
For me I think it just hid another exception (related to transaction scopes) — once I fixed the transaction scope issue I did not encounter this NRE again.

I'm not in need of an urgent fix.

Thanks for your awesome work!

**Comment by erwin-faceit** [comment]
I'll close this for now, but I'm interested in why it gave you an exception in the first place. Perhaps you can share a piece of code?

**Comment by PaulARoy** [comment]
Honnestly I don't really know why it happened, basically I was trying to launch the job inside a TransactionScope that had the wrong level of isolation (isolation level changed on 1.7 and I didn't know I had to update it). 
That was throwing an exception inside the Hangfire library but it was then hidden by the Hangfire.Tag NRE.

A pretty messed up scenario, I highly doubt it would happen in a normal case.

The code could be summarized like:
```
SqlAzureConfiguration.SuspendExecutionStrategy = true; 
using (var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
    BackgroundJob.Enqueue<HangfireTaskHelper>(hth => hth.SomeMethodWithATagAnnotationAsync(null, someArgument));
}
```

Which was fixed by adding:

```
SqlAzureConfiguration.SuspendExecutionStrategy = true; 
using (var transaction = new TransactionScope(TransactionScopeOption.Required, 
                                              new TransactionOptions() { IsolationLevel = IsolationLevel.ReadCommitted }, 
                                              TransactionScopeAsyncFlowOption.Enabled))
{
    BackgroundJob.Enqueue<HangfireTaskHelper>(hth => hth.SomeMethodWithATagAnnotationAsync(null, someArgument));
}
```
