### ISSUE TITLE
Not all tags are searchable

### ISSUE THREAD

**Issue by jfantunes** [face-it/Hangfire.Tags#20]
Hi!
When I try to add a tag using a date time format but in string like 25/05/2020 my tag is added in this format 25052020, but this is not a problem. The main problem is that when i try to search using dropdown or the click it doesnt appear but it's been added since the tag number increases.

The following code is this one

```
internal virtual void SetBackgroundTaskContextTags(string[] tags)
        {
            var currentDateTag = DateFunctions.ConvertDateToStringFormat(DateTime.Now, "d");
            var tagsWithCurrentDate = tags.Append(currentDateTag);
            BackgroundContext.AddTags(tagsWithCurrentDate);
        }
```

Any thoughts why this happen?

**Comment by erwin-faceit** [comment]
Can you query the Hangfire.Set table, and see which value is stored there?

**Comment by erwin-faceit** [comment]
Also, let me know what BackgroundContext is referring to. Is it the PerformContext, or something different? I myself use a custom hangfire filter to add the current date to all jobs that I run (in the format yyyyMMdd), but that works as designed.

**Comment by jfantunes** [comment]
The value for the tags stored is 05212020 for instance. I also saw another values like 5182020. 
It seems like a valid string, why doesn't appear?
Also erwin can you show how are you doing with the filter?

**Comment by erwin-faceit** [comment]
Define a class like this:

```
using System;
using Hangfire.Server;
using Hangfire.Tags;

namespace Hangfire.Tags.Attributes
{
    internal class DailyTagAttribute : IServerFilter
    {
        public void OnPerforming(PerformingContext  filterContext)
        {
            filterContext.BackgroundJob.Id.AddTags(DateTime.Now.Date.ToString("yyyy-MM-dd"));
        }

        public void OnPerformed(PerformedContext filterContext)
        {
        }
    }
}
```

and add this line of code near your hangfire initialization:
```
GlobalJobFilters.Filters.Add(new DailyTagAttribute());
```

**Comment by erwin-faceit** [comment]
Is the problem with searching always the values which are padded with a zero? Also, what storage are you using?

**Comment by erwin-faceit** [comment]
Too long no comment - closing
