### ISSUE TITLE
Last Execution not showing

### ISSUE THREAD

**Issue by agausachs** [face-it/Hangfire.Tags#24]
In the tasks list, after selecting a tag, the "last execution" column is shown but is empty.

Thanks!

**Comment by erwin-faceit** [comment]
Can you give me a bit more information about your setup? With the SQL provider this works as designed.

![image](https://user-images.githubusercontent.com/43995928/88578341-b02a3400-d048-11ea-9bfc-9e9b887e06a5.png)

**Comment by agausachs** [comment]
Hi!

I can see the code below. The last column (where the time is supposed to be) is empty.

My database configuration is Microsoft SQL Server 2012 - 11.0.5058.0 (X64) Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

I also use the nuget packages Hangfire.Console, Hangfire.Dashboard.Management and Hangfire.MissionControl.

Thanks in advance!

**IMAGE:**
![lastExecution](https://user-images.githubusercontent.com/7044534/88887844-7ff7b680-d23d-11ea-86d0-9854e0ef5002.png)

**CODE:**

                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="min-width">
                                        <input type="checkbox" class="js-jobs-list-select-all" />
                                    </th>
                                    <th class="min-width">Id</th>
                                    <th>Tarea</th>
                                    <th class="min-width">Estado</th>
                                    <th class="align-right">&#218;ltima ejecuci&#243;n</th>
                                </tr>
                            </thead>
                            <tbody>
                                    <tr class="js-jobs-list-row">
                                        <td>
                                            <input type="checkbox" class="js-jobs-list-checkbox" name="jobs[]" value="2385" />
                                        </td>
                                        <td class="min-width">
                                            <a href="/hangfire/jobs/details/2385">#2385</a>
                                        </td>

                                            <td class="word-break">
                                                <a class="job-method" href="/hangfire/jobs/details/2385">Actualitza MCFs</a>
                                            </td>
                                            <td class="min-width">
                                                Succeeded
                                            </td>
                                            <td class="min-width align-right">
                                            </td>
                                    </tr>
                            </tbody>
                        </table>
                    </div>

**Comment by erwin-faceit** [comment]
Just out of curiosity, can you execute the query:

select Data from Hangfire.State where JobId=2385

**Comment by agausachs** [comment]
This is the result (3 rows):
{"EnqueuedAt":"1596013737644","Queue":"mcfs"}
{"StartedAt":"1596013737760","ServerId":"esmad09693:25112:22265c71-430f-432f-bf3e-3775ec5de1f6","WorkerId":"5228cdd0-5db8-4b41-bf65-9f8e9c50139e"}
{"SucceededAt":"1596013740150","PerformanceDuration":"2268","Latency":"238"}

**Comment by erwin-faceit** [comment]
That is interesting! For me, that data contains actually datestamps, but in your case, apparently timestamps are used:

{"SucceededAt":"2020-06-23T14:37:04.2648427Z","PerformanceDuration":"8721","Latency":"93233"}

Since Hangfire.Tags parses the datestring, I can imagine that this will fail. I'll take a look into this!

**Comment by erwin-faceit** [comment]
Just found out that this has to do with a different compatibility mode: https://github.com/HangfireIO/Hangfire/blob/a07ad0b9926923db75747d92796c5a9db39c1a87/src/Hangfire.Core/Common/JobHelper.cs#L80

A fix is on it's way, it'll be a provider only fix (so Hangfire.Tags.MySql.Official, Hangfire.Tags.SqlServer or Hangfire.Tags.PostgreSql, version 1.6.4).

**Comment by agausachs** [comment]
Great!! Thanks!!
