### ISSUE TITLE
"Loading Tags..." in Dashboard Jobs Details Page

### ISSUE THREAD

**Issue by agausachs** [face-it/Hangfire.Tags#25]
Although I can see the tags options in the dashboard menu, with the counter, and I can search by one of them, when I access to a job details page it appears a static message that says "Loading Tags...". If I go to Chrome inspector, there's a call to http://myhangfireservername:port/tags/THEJOBID with an Internal Server Error (500) with no more details in the response.

**Comment by jfantunes** [comment]
I also see the tag options in the menu, but when i try to open it says to me that the page couldn't be open. The strange is that before the update all was working fine. It has anything to do with the last update or we have to change something on the configuration?
My code to setup the tags is the following one:^


 services.AddHangfire(configuration =>
         {
configuration.UseTagsWithPostgreSql(new TagsOptions()
                {
                    TagsListStyle = TagsListStyle.Dropdown,
                    Storage = new PostgreSqlTagsServiceStorage(new PostgreSqlStorageOptions()
                    {
                        PrepareSchemaIfNecessary = true,
                        SchemaName = BackgroundJobConfigurations.DatabaseTagsSchema
                    })
                });
});

**Comment by mellamokb** [comment]
@agausachs 
I had this issue on our server after installing HangFire Tags.  I was able to get more details on the 500 error, and it referenced wrong version of NewtonSoft.Json library.  I updated NewtonSoft.Json to latest version for our entire solution, and it resolved the issue.  That might be something to try.

**Comment by agausachs** [comment]
Thanks @mellamokb ! You are indeed right. I have upgraded NewtonSoft.Json to version 12, and now I can see the tags in the jobs details page.
