### ISSUE TITLE
Suggestion: Allow clicking Tag on job view

### ISSUE THREAD

**Issue by mellamokb** [face-it/Hangfire.Tags#27]
When viewing an existing job in the Hangfire UI, it shows the list of tags associated with that job at the top.  It would be really helpful if you could maybe click on the tag, and it would take you to the tag search interface, filtered for the tag you clicked on.  Quick and easy way to find other jobs associated with that tag.

**Comment by erwin-faceit** [comment]
That should've been a feature from the start. In my mind it was, but thanks for reminding me. I've added a clickable tag.

**Comment by mellamokb** [comment]
Hey just wanted to respond, I am using this feature and it works beautifully. Thanks again for your efforts!

Best Regards,
