### ISSUE TITLE
Tags are lost after some time

### ISSUE THREAD

**Issue by agust220** [face-it/Hangfire.Tags#30]
I've been looking at my failed queue and noticed that some jobs are there but when I click to view them they have no Tags and are not visible under the Tag to which they should. 

- Scrolling down 3000 failed jobs I find 30 jobs which should have the tags **X**, **Y** and **Z**
- Viewing **Tags** and looking at my three tags I see one failed job (executed 9 hrs ago) which has all 3 tags.

Is there an expiration date to the tags and if so is it customizable, and shouldn't the tags be visible if the job can still be previewed in the failed queue explorer?

Version: 1.6.3

**Comment by erwin-faceit** [comment]
By default, tags are expired using the JobExpiration timeout setting of Hangfire, as you can [see here](https://github.com/face-it/Hangfire.Tags/blob/a7a1778dde0ba51dd265595825b56c9ae2fd2d8c/src/Hangfire.Tags/States/TagsCleanupStateFilter.cs#L17).

Can you verify this in the database? The table [Hangfire].[Set] has an ExpireAt column, which should either have a value in the future, or be null.

**Comment by agust220** [comment]
> Can you verify this in the database?

Yes I can see that some have the value _NULL_ and some a date in the future.
Unfortunately another member of my team cleared the failed queue this morning.

Is it possible to override the timeout setting via a custom filter or other?

**Comment by erwin-faceit** [comment]
The query below should give you no results. 
```
select * from Hangfire.[Set] s
	inner join Hangfire.[Job] j ON s.Value=CAST(j.Id AS VARCHAR)
 where s.ExpireAt IS NOT NULL AND [Key] like 'tags:%' AND DATEDIFF(second, s.ExpireAt, j.ExpireAt) > 1
```

There may be a small difference between the two expiry times, but that should be it. If you get any records, then I'm interested in that. 

At the moment, it's not possible to override the expiration time of tags. That wouldn't really make sense, since it's designed to be the same as the job expiration.

Is this only happening with failed jobs? And what is your global hangfire configuration?

**Comment by agust220** [comment]
The issue is most likely resolved. Another website of mine which also schedules jobs for execution did not have the **Hangfire.Tags** package installed but did not produce any error. I will close this issue as soon as I have verified that this is the issue.

**Comment by erwin-faceit** [comment]
I'll close this for now. If you have any information about this issue, feel free to reopen, or create a new one!
