### ISSUE TITLE
MySqlException: Table 'HangfireStorage.HangfireTagSet' doesn't exist

### ISSUE THREAD

**Issue by jieke-wang** [face-it/Hangfire.Tags#33]
![20210120171549](https://user-images.githubusercontent.com/12584587/105153412-5dd35700-5b43-11eb-8ba6-7f907d2f0fa5.png)

TargetFramework: net5.0

Hangfire.AspNetCore: 1.7.18
Hangfire.Core: 1.7.18
Hangfire.MySqlStorage: 2.0.3
Hangfire.Tags.MySql.Official: 1.7.0

**Comment by erwin-faceit** [comment]
It seems that you've set a different TablePrefix for Hangfire.Tags as for Hangfire. Make sure the prefix for both are the same, since Hangfire.Tags uses the Hangfire tables to store the information.

If that's not the case, then please post your configuration.
