### ISSUE TITLE
Invalid object name 'HangFire.Set'.

### ISSUE THREAD

**Issue by migochoa73** [face-it/Hangfire.Tags#34]
I use SchemaName, in both, dashboard and server, but the error try to find the "HangFire" schema and ignore the SchemaName in the settings

**Comment by migochoa73** [comment]
This error happen when I do click in Tag link the dashboard

**Comment by erwin-faceit** [comment]
Which backend are you using? Can you post your configuration and version information?

**Comment by migochoa73** [comment]
My backend is ASP.NET MVC .NetFremework 4.7.2, SQLServer

`Imports Owin
Imports Microsoft.Owin
Imports Hangfire
Imports Hangfire.Dashboard
Imports Hangfire.Annotations
Imports Hangfire.Console
Imports Hangfire.Tags
Imports Hangfire.Tags.SqlServer


<Assembly: OwinStartupAttribute(GetType(Startup))>

Partial Public Class Startup

    Public Sub Configuration(app As IAppBuilder)
        GlobalConfiguration.Configuration.UseSqlServerStorage(ConfigurationManager.ConnectionStrings("SQLConnection").ConnectionString, New Hangfire.SqlServer.SqlServerStorageOptions With {
                .CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
                .SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
                .QueuePollInterval = TimeSpan.Zero,
                .UseRecommendedIsolationLevel = True,
                .UsePageLocksOnDequeue = True,
                .DisableGlobalLocks = True,
                .SchemaName = "SBQ",
                .PrepareSchemaIfNecessary = True
            })

        GlobalConfiguration.Configuration.UseTagsWithSql(New TagsOptions With {
            .TagsListStyle = TagsListStyle.Dropdown
        })

        GlobalConfiguration.Configuration.UseConsole()

        app.UseHangfireDashboard("/workers", New DashboardOptions With
                {
                    .DisplayStorageConnectionString = False,
                    .DashboardTitle = "Workers",
                    .AppPath = VirtualPathUtility.ToAbsolute("~"),
                    .Authorization = New List(Of IDashboardAuthorizationFilter) From {New HangFireAuthorizationFilter}
                })
    End Sub
End Class

`

I test removing SchemaName  in the same DB and work fine with the default Schema, but using ShemaName not, only when I click the opntion Tags in the dashboard give me the error.

**Comment by erwin-faceit** [comment]
And do you also have a stacktrace?

**Comment by erwin-faceit** [comment]
Oh wait...if you're using a different schemaname, then pass that along explicitly to the UseTagsWithSql constructor as well. We can only use the default options, but not retrieve it from the SQL JobStorage that HangFire uses internally.

**Comment by migochoa73** [comment]
`Dim SqlOptions As New Hangfire.SqlServer.SqlServerStorageOptions With {
                .CommandBatchMaxTimeout = TimeSpan.FromMinutes(5),
                .SlidingInvisibilityTimeout = TimeSpan.FromMinutes(5),
                .QueuePollInterval = TimeSpan.Zero,
                .UseRecommendedIsolationLevel = True,
                .UsePageLocksOnDequeue = True,
                .DisableGlobalLocks = True,
                .SchemaName = "SBQ",
                .PrepareSchemaIfNecessary = True
            }

        GlobalConfiguration.Configuration.UseSqlServerStorage(ConfigurationManager.ConnectionStrings("SQLConnection").ConnectionString, SqlOptions)

        GlobalConfiguration.Configuration.UseTagsWithSql(New TagsOptions With {
            .TagsListStyle = TagsListStyle.Dropdown
        }, SqlOptions)`

I create a variable to store SqlOptions and pass to both configurations, and it work perfect

Thank you
