### ISSUE TITLE
Orphaned Tags Cleanup

### ISSUE THREAD

**Issue by mellamokb** [face-it/Hangfire.Tags#36]
Hi :)

I have been running smoothly with Tags here for a number of months now.  I'm sorry I haven't followed up on the other requests, I should be able to now that we are out of our busy season.  Thanks again for your efforts!

I'm noticing now I still have around 550K tags, even though a few months back, I removed one of the tag sources (email id) which was adding a bunch of useless tags (my own fault).  The vast majority of those tags were one-time use and associated with jobs that have long since finished, expired, and been deleted.  I believe I have our successful jobs configured to delete after 30 days.

Is there an easy way to check for all tags which have no associated job and clean them up out of the database?  Is there some configuration as well that would automatically cleanup any tags when a job is cleaned up?

Thanks!

**Edit:** It is causing a bit of performance issue using the Tags screen is why I ask.  It is taking around 10 seconds to open tags screen.

**Comment by erwin-faceit** [comment]
So, what basically (should) happen is that the TagsCleanupStateFilter is added to the state filters in Hangfire. Once a job receives a Final state, we set the expiration time of the job using the JobExpirationTimeout configuration. If the received state is not a final state, we'll reset the expiration time. The only "final" states Hangfire has are Deleted and Succeeded.

The tags itself are stored in the Set table, and we store them twice: once using the Key 'tags:<jobid>', which has all the tags as Values, and also the other way around, where the Key is 'tags:<tag>' and the Value is a <jobid>. So in order to find all "obsolete" tags, you could use a query like this (MSSQL, and not the most optimized, and very long, etc. etc.):

```sql
SELECT s.* FROM (
	SELECT s.* FROM (
		SELECT s.[Key], s.JobId FROM (
			SELECT DISTINCT s.[Key], SUBSTRING(s.[Key], 6, 10) AS JobId 
				FROM Hangfire.[Set] s 
				WHERE s.[Key] LIKE 'tags:%' 
				AND TRY_CAST(SUBSTRING(s.[Key], 6, 10) AS int) IS NOT NULL
		) s
		LEFT JOIN HangFire.[Job] j ON j.Id=s.JobId
		WHERE j.Id IS NULL
	) expired 
	CROSS APPLY (SELECT * FROM HangFire.[Set] s WHERE s.[Key] = expired.[Key]) s
) s 
UNION
SELECT s.* FROM (
	SELECT s.* FROM (
		SELECT s.[Key], s.JobId FROM (
			SELECT DISTINCT s.[Key], SUBSTRING(s.[Key], 6, 10) AS JobId 
				FROM Hangfire.[Set] s 
				WHERE s.[Key] LIKE 'tags:%' 
				AND TRY_CAST(SUBSTRING(s.[Key], 6, 10) AS int) IS NOT NULL
		) s
		LEFT JOIN HangFire.[Job] j ON j.Id=s.JobId
		WHERE j.Id IS NULL
	) expired 
	CROSS APPLY (SELECT * FROM HangFire.[Set] s WHERE s.[Key] like 'tags:%' AND s.[Value]=expired.[JobId]) s
) s```

On my setup, which has 802.894 tags, this returns 144 rows (which is 144 too many).

Anyway, the system relies on the expiry column in the Set, and HangFire itself should delete all the entries.

Can you tell me your setup, and whether or not the expiry column is empty.

**Comment by mellamokb** [comment]
OK - That query only returns 1 row, which is probably because it took 3-4 minutes to run and a job finished in the middle of the query.  But when I check distinct keys of 'tags:%' which are not job ids, there is only around 56K.  However this query returns the 564K total count that I get for tags.

```sql
select distinct [value] from [Hangfire].[Set] where [Key] like 'tags'
```

Are those potentially including any tag that was ever used once, but not removing them once the last reference to that tag is removed?  The search seems smart enough to leave them out if they have no jobs associated, but I'm wondering if all those unused tags cause performance issues and bloated tag count on the dashboard?

**Comment by erwin-faceit** [comment]
I'm really not sure this is bloat, to be honest, but let me try to explain from my point of view. Also, the 1 row and the 3-4 minutes are unrelated. It's a nasty query, but it should return all rows that should be expired.

So, the difference between distinct keys and amount of records makes sense to me, depending on the amount of tags per job, and the amount of jobs. For example, if I have 2 jobs (Job A with id 1 and Job B with id 2) and both have 2 tags (Tag T1 and Tag T2), I'll end up with these rows:

key | value
--- | ---
tags:1 | T1
tags:1 | T2
tags:T1 | 1
tags:T2 | 1
tags:2 | T1
tags:2 | T2
tags: T1 | 2
tags:T2 | 2

This seems a bit "redundant", but that's how HangFire stores sets internally. In this scenario (2 jobs with each 2 tags), the amount of distinct keys is 4, and the amount of rows is 8.  

When, for instance, I'm adding another tag to one of the jobs, it would result in 2 additional rows. Or when I add another job with the same two tags, 
Now, if one job was to get another tag, it would add 2 more rows. If I get another job with two tags, I would get an additional 4 rows (amount of tags * 2).

So, is there a chance that you are using quite a few tags, or have quite a few jobs?

**Comment by mellamokb** [comment]
Thanks for the response.  I understand the redundancy and have no problem with that!  What I'm talking about, I think not saying very clearly, there appears to be a third category of records in the table like this where the key is simply 'tags':

| key      | value |
| ------ | ------- |
| tags      | T1       |
| tags   | T2        |
| tags      | T3       |
| tags   | T4        |

But there are extras, like T3 and T4 that are not linked to any jobs at all.  I seem to have around 508,000 extra rows in Set table of this format, using tags that were once used months ago, but are no longer linked to any jobs and never will be again because I have changed my tagging strategy.  Can I simply remove those 508,000 extra rows?

Thanks!

**Edit:** Certainly I do have a very large number of jobs and tags so I understand that is going to take some performance for sure.  Currently sitting at 7.2M successful job history, 16K pending, and probably every job has at least 2-3 tags.  A quick check number of records in [Set] table with Key like 'tags%' sits at ~1.8M.

**Comment by erwin-faceit** [comment]
Now I got it...and you're absolutely right! You can safely delete those tags, and I've just pushed a commit that should fix this issue (forgot to tag it though).
