### ISSUE TITLE
System.LoadType Exception - MySQL Storage

### ISSUE THREAD

**Issue by rob893** [face-it/Hangfire.Tags#37]
Target framework .NET 5.

Config:
![image](https://user-images.githubusercontent.com/20483475/108951705-5826d080-761d-11eb-9fa0-f1a95ae17864.png)

Dependencies and packages versions:
![image](https://user-images.githubusercontent.com/20483475/108951639-34638a80-761d-11eb-9df6-7c95996d9ffc.png)

Exception:
![image](https://user-images.githubusercontent.com/20483475/108951567-0ed68100-761d-11eb-85f5-72410c647b5a.png)

**Comment by erwin-faceit** [comment]
This is not an issue with Hangfire.Tags, but I think you may find more information here: https://github.com/Mimetis/Dotmim.Sync/issues/420

**Comment by rob893** [comment]
Oh interesting. Thanks!
