### ISSUE TITLE
Tags do not appear in Dashboard until execution

### ISSUE THREAD

**Issue by HarleeDavidson** [face-it/Hangfire.Tags#41]
I thought I might see tags in the dashboard for scheduled jobs, but only see tags for jobs after execution begins. Is this by design?

**Comment by erwin-faceit** [comment]
It depends. If you're using the AddTags extension method, then yes. If you're using the TagAttribute, then make sure that both service and scheduling application have a UseTags when setting up. 

Can you share some code, so that I can give a more detailed reaction?

**Comment by HarleeDavidson** [comment]
Yes, when using the AddTags extension method, the tags do of course become visible after execution begins. 

As it happened though, I was using the same tag values in the Tag attribute. At first it appeared to to be a timing issue until I did some more experimentation where I may have found a pattern.

We are using an abstract class to define a DoWork method, and using an implementation class to perform the desired work. For example:

```
[Hangfire.Tags.Attributes.Tag("AWorker")]
public abstract class AWorker
{
	public void DoWork()
	{
		OnDoWork();
	}
	public abstract void OnDoWork();
}

[Hangfire.Tags.Attributes.Tag("MyWorker")]
public class MyWorkerClass : AWorker
{
	public override void OnDoWork()
	{
		// do the work for this implementation
	}
}
```
In this scenario, the "AWorker" tag is registered but not the "MyWorker" tag.

**Comment by HarleeDavidson** [comment]
I've found that in the class: 
[Hangfire.Tags.States.CreateJobFilter](https://github.com/face-it/Hangfire.Tags/blob/332c6cb8b688d4133794f5d6ed79f607443cae29/src/Hangfire.Tags/States/CreateJobFilter.cs)

Changing 
```
var attrs = mi.GetCustomAttributes<TagAttribute>()
	.Union(mi.DeclaringType?.GetCustomAttributes<TagAttribute>() ?? Enumerable.Empty<TagAttribute>())
	.SelectMany(t => t.Tag).ToList();
```
to
```
var attrs = mi.GetCustomAttributes<TagAttribute>()

	/*  Added this line to include Tag Attributes defined within the implementation class.  */
	.Union(filterContext.BackgroundJob.Job.Type?.GetCustomAttributes<TagAttribute>() ?? Enumerable.Empty<TagAttribute>())
	
        .Union(mi.DeclaringType?.GetCustomAttributes<TagAttribute>() ?? Enumerable.Empty<TagAttribute>())
	.SelectMany(t => t.Tag).ToList();
```
did the trick for me.

This works equally well for ordinary classes as well.

**Comment by erwin-faceit** [comment]
Good job! Is it possible to create a PR for this?

**Comment by HarleeDavidson** [comment]
Added [PR #42  ](https://github.com/face-it/Hangfire.Tags/pull/42)
