### ISSUE TITLE
Cannot use tags on multiple dashboards

### ISSUE THREAD

**Issue by VitaliiBushylo** [face-it/Hangfire.Tags#43]
Hello,
I'm hosting multiple dashboards in a single .NET Core 3.1 web application. Hangfire servers are hosted separately. Dashboards use different SQL storages. 
Dashboards show the correct number of tags for each of them.
![image](https://user-images.githubusercontent.com/27290203/115101372-7fe93500-9ef8-11eb-86fd-f57cd1f05643.png)
When I click on the Tags tab I get the following error.
![image](https://user-images.githubusercontent.com/27290203/115266446-10886680-a0ed-11eb-9570-8f160505365f.png)

I tried to configure multiple SQL storages in GlobalConfiguration. The exception was gone but both dashboards display tags from the latest storage that I registered.

Please advise how to configure tags for multiple dashboards in a single app for distributed environment.

Thank you!

**Comment by erwin-faceit** [comment]
Interesting case. I had no idea that you could host multiple dashboards in one application. Is it simple to make a sample application for that?  Perhaps you can add some configuration, so that I can reproduce this.

**Comment by VitaliiBushylo** [comment]
[Hahgfire.Core.Distributed.zip](https://github.com/face-it/Hangfire.Tags/files/6330116/Hahgfire.Core.Distributed.zip)

Hi @erwin-faceit, thank you for quick response.
I've attached the solution that has minimal required implementation to demonstrate my use case. 
For storages I used localdb. The solution consists of four projects: two servers, common library that hosts recurring jobs interfaces, and web app that hosts multiple dashboards.

Kindly review.
Looking forward to hearing from you.

**Comment by VitaliiBushylo** [comment]
Forgot to describe steps to reproduce the issue.

In case you already have two different Hangfire storages (with tags) then you need: 
1. Update  two connection strings in the Startup class of the 'MultipleDashboards' project and run only this single project.
2. In order to open the dashboard follow one of the links that are present on a default page.
3. Click on Tags tab.

In case you don't have ready to use storages then:
1. Create two databases.
2. Update connection strings in all three projects in Startup classes.
2. Run all three projects. Let them to work several minutes.
3. Switch over the page that belongs to the 'MultipleDashboards' project.
4. In order to open the dashboard follow one of the links that are present on a default page.
3. Click on Tags tab.

Hope this helps.

**Comment by VitaliiBushylo** [comment]
Hi @erwin-faceit. 
I've implemented a hotfix for this issue. Can I create a pull request? Unless you have other proposition.

**Comment by erwin-faceit** [comment]
That would be really nice. I was a bit swamped with work the last few days. Thanks in advance!

**Comment by VitaliiBushylo** [comment]
I used master branch for experimenting. Should I create PR to the develop branch instead?

**Comment by VitaliiBushylo** [comment]
@erwin-faceit I'm trying to push changes to a separate branch in order to create PR. Seems like I don't have permissions to do so. Please advice what do I do wrong here?
![image](https://user-images.githubusercontent.com/27290203/115618540-b41d7680-a2a7-11eb-98e1-ce6f7eced8b0.png)

**Comment by erwin-faceit** [comment]
You should press Fork in the top right corner, that should give you a copy of this repo under your own account. You can push your changes there. After that, you can submit a PR from there.

**Comment by VitaliiBushylo** [comment]
Kindly review the PR https://github.com/face-it/Hangfire.Tags/pull/46
Proposal to support Tags on multiple dashboards that are hosted in a single application.

**Comment by erwin-faceit** [comment]
Thank you for your excellent PR and sample application. I never knew that this was possible. I'll review the PR, but I would love to solve this using the internal multiplexer of Hangfire itself. I'm pretty busy at the moment, but I already have pulled the PR, and tried some things out. Looks pretty decent, thanks for your hard work!

**Comment by VitaliiBushylo** [comment]
Thank you for evolving the project. Tags are very helpful when have to deal with many jobs.
Looking forward for new release!
