### ISSUE TITLE
How to allow .net 4.5 for Hangfire.Tags.SqlServer

### ISSUE THREAD

**Issue by mcockrellsana** [face-it/Hangfire.Tags#45]
Hello!

I know that the standard Hangfire.Tags allows for .net 4.5 - but I noticed that the Hangfire.Tags.SqlServer does not allow for .net 4.5. 

As I don't have the option to upgrade the .net 4.5 version for reasons out of my hands, is there any information one can give to be able to enable that project to be usable in a .net 4.5 environment?

**Comment by erwin-faceit** [comment]
You should be able to compile the project yourself for .NET 4.5, I think.

**Comment by mcockrellsana** [comment]
I ended up having to bring the project down as you said, but had to make quite a few changes to get the project to work in a .net 4.5 environment (a lot of things were using System.Data.SqlClient from a newer version of that).  But I was able to refactor everything.

Unrelated question, is there a way to programmatically tag a job when it is scheduled/enqueued without using attributes?  I can't use attributes as when my service schedules the job, it receives job information that helps me tag the job with specific unique information that wouldn't be allowed by the attribute (unless the attribute allows for inline insertion like the DisplayName one does for Hangfire, i.e. [DisplayName("Something - {0}"])  If I need to submit another issue/question I can do so no problem.

**Comment by mcockrellsana** [comment]
I answered my own question by just testing it out, it indeed does work!  Awesome!

Sorry for the needless question!

**Comment by mcockrellsana** [comment]
Also, if you want/need the updated Tags.SqlServer implementation, I can put it up somewhere and provide a link for others who might encounter the same issue.

**Comment by erwin-faceit** [comment]
We might be able to make the current implementation target both versions, and use compile directives to correctly compile. I'd say: yes please! Are you able to create a PR with adjusted version as a new project? Then I can update that PR to combine both projects. That would be really awesome. 

If that's too much trouble, please use any other method. Thanks in advance!
