### ISSUE TITLE
Sql query error on GetJobs

### ISSUE THREAD

**Issue by muhammetustaoglu** [face-it/Hangfire.Tags#48]
In the query, one field in the join statement is "id" instead of "Id". This cause application error

**Comment by erwin-faceit** [comment]
With what type of database? I’ve not seen this error before.

**Comment by muhammetustaoglu** [comment]
We try this on MS Sql Server.

**Comment by muhammetustaoglu** [comment]
SqlTagsServiceStorage.cs page line 104 and 205. Can you fix the lines and create new version please? We would like to use this nuget package. Besides, hangfire version is also a little bit old. May be you can update it either.

**Comment by erwin-faceit** [comment]
We use this on MSSql in production for a few years now. What is the database collation used? If that contains CS, can you change that to CI?

**Comment by muhammetustaoglu** [comment]
Our database collation is "Turkish_CI_AS", so im sorry but it is already case insensitive

**Comment by erwin-faceit** [comment]
I’ll try to create a reproduction of this issue, but am on holiday this week.

**Comment by erwin-faceit** [comment]
I’m a bit surprised though:

`The way to determine if a database or database object is to check its "COLLATION" property and look for "CI" or "CS" in the result. The CI indicates that the server is case insensitive.`

**Comment by muhammetustaoglu** [comment]
It's ok. I have no rush. I'll create a PR. Review it when you have time. Btw, nice feature. Congrats!

**Comment by muhammetustaoglu** [comment]
Since i'm not authorized, i cant create PR. :(

**Comment by muhammetustaoglu** [comment]
Hello,
Did you have chance to debug the issue?

**Comment by erwin-faceit** [comment]
Sorry for the late reaction to this, caught up in regular work. I've just pushed an update of the components.

About updating the Hangfire version: usually packages reference the lowest possible version to maintain compatibility with older projects. You're free to use a higher version though, it should give no problems whatsoever.
