### ISSUE TITLE
Null Reference Exception after increasing aws redis instance size. 

### ISSUE THREAD

**Issue by jasonarcala-petdesk** [face-it/Hangfire.Tags#49]
This exception started happening after upsizing our aws redis instance from a t3.micro to t3.small. Due this error, Hangfire Background jobs couldn't be created. 

Work around: Deploy with tags plugin disabled. Reenable tags and redeploy. 

`[22:55:59.686 ERR][***] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request. {EventId={Id=1, Name="UnhandledException"}, RequestPath="/api/Job/RecreateDefault", ConnectionId="0HMHFLLIL4HD6", ExceptionDetail={["HResult"]=-2146233088, ["Message"]="Background job creation failed. See inner exception for details.", ["Source"]="Hangfire.Core", ["InnerException"]={["Type"]="System.NullReferenceException", ["Data"]={["OriginalStackTrace"]="   at Hangfire.Tags.States.CreateJobFilter.OnCreated(CreatedContext filterContext)\n   at Hangfire.Client.BackgroundJobFactory.InvokeOnCreated(Tuple`2 x)"}, ["HResult"]=-2147467261, ["Message"]="Object reference not set to an instance of an object.", ["Source"]="Hangfire.Tags"}, ["Type"]="Hangfire.BackgroundJobClientException"}}`

I'm not a 100% sure, but it might be due to this line: 
https://github.com/face-it/Hangfire.Tags/blob/c6427e5dd1d0357fa8f087625c422aa2762f8a37/src/Hangfire.Tags/States/CreateJobFilter.cs?msclkid=c167ff66ce6311ecaef71b2a9daeade1#L28

**Comment by erwin-faceit** [comment]
I really have no idea about this one. I don't have AWS myself, so I can't test this. The line specified can only fail if the data inside Redis is at some point not complete (e.g. during a migration), but I have no idea how AWS executes such an upgrade.

What's really weird is that is works after a redeploy disabling and enabling Hangfire.Tags. Hangfire.Tags doesn't have any state on it's own, no schema changes or whatever are required, it's all just plain Hangfire. 

For me, this is too much of a far-fetched issue, which I can't reproduce, which means I won't be putting any time in. If this issue pops up again, I'll reconsider. In the mean time, if you have the time for it, feel free to create a pull request. 😎
