### ISSUE TITLE
TablePrefix  bug

### ISSUE THREAD

**Issue by mingyangzhu** [face-it/Hangfire.Tags#5]
I set TablePrefix=“_hangfire”  ，then click Jobs->Tags menu ,throw  MySqlException: Table 'qcdataprocessor.hangfire_set' doesn't exist。
i use this code repository:
https://github.com/yuzd/Hangfire.HttpJob/blob/master/Hangfire.Tags.Mysql/Hangfire.Tags.Mysql.csproj 

this is code:
	//hangfire
			services.AddHangfire(op =>
			{
				op.UseStorage(new MySqlStorage(Configuration["ConnectionStrings:DataProcessor"], new MySqlStorageOptions
				{
					TransactionIsolationLevel = System.Data.IsolationLevel.ReadCommitted,
					QueuePollInterval = TimeSpan.FromSeconds(15),
					JobExpirationCheckInterval = TimeSpan.FromHours(1),
					CountersAggregateInterval = TimeSpan.FromMinutes(5),
					PrepareSchemaIfNecessary = true,
					DashboardJobListLimit = 50000,
					TransactionTimeout = TimeSpan.FromMinutes(1),
					TablePrefix = "_hangfire",
				}));
				op.UseTagsWithMysql();
			});

this is detail  error :
An unhandled exception occurred while processing the request.
MySqlException: Table 'qcdataprocessor.hangfire_set' doesn't exist
MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in ResultSet.cs, line 146

MySqlException: Table 'qcdataprocessor.hangfire_set' doesn't exist
MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in MySqlDataReader.cs, line 74

TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)

Stack Query Cookies Headers
MySqlException: Table 'qcdataprocessor.hangfire_set' doesn't exist
MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in ResultSet.cs

Show raw exception details
MySqlException: Table 'qcdataprocessor.hangfire_set' doesn't exist
MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in MySqlDataReader.cs
MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in MySqlDataReader.cs
MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in MySqlDataReader.cs
MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(string commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in TextCommandExecutor.cs
MySql.Data.MySqlClient.MySqlCommand.ExecuteScalarAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in MySqlCommand.cs
MySql.Data.MySqlClient.MySqlCommand.ExecuteScalar() in MySqlCommand.cs
Dapper.SqlMapper.ExecuteScalarImpl<T>(IDbConnection cnn, ref CommandDefinition command) in SqlMapper.cs
Dapper.SqlMapper.ExecuteScalar<T>(IDbConnection cnn, string sql, object param, IDbTransaction transaction, Nullable<int> commandTimeout, Nullable<CommandType> commandType) in SqlMapper.cs
Hangfire.Tags.Mysql.MysqlTagsServiceStorage+<>c__DisplayClass6_0.<SearchWeightedTags>b__0(DbConnection connection)
Hangfire.MySql.Core.MySqlStorage+<>c__DisplayClass20_0<T>.<UseTransaction>b__0(MySqlConnection connection)
Hangfire.MySql.Core.MySqlStorage.UseConnection<T>(Func<MySqlConnection, T> func)
Hangfire.MySql.Core.MySqlStorage.UseTransaction<T>(Func<MySqlConnection, T> func, Nullable<IsolationLevel> isolationLevel)
Hangfire.MySql.Core.Monitoring.MySqlMonitoringApi.UseConnection<T>(Func<MySqlConnection, T> action)

Show raw exception details
TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
System.Reflection.MethodBase.Invoke(object obj, object[] parameters)
Hangfire.Tags.Mysql.MysqlTagsMonitoringApi.UseConnection<T>(Func<DbConnection, T> action)
Hangfire.Tags.Mysql.MysqlTagsServiceStorage.SearchWeightedTags(string tag, string setKey)
Hangfire.Tags.Storage.TagsStorage.SearchWeightedTags(string tag)
Hangfire.Tags.Dashboard.Pages.TagsSearchPage.Execute()
Hangfire.Dashboard.RazorPage.TransformText(string body)
Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Show raw exception details

**Comment by erwin-faceit** [comment]
First off, sorry for the late reply, I'll have to fix notifications somehow. I'm not getting them.

I think you're going to have to pass the MySqlOptions to the UseTagsWithMySql method as well:

```
var options = new MySqlStorageOptions
{
    TransactionIsolationLevel = System.Data.IsolationLevel.ReadCommitted,
    QueuePollInterval = TimeSpan.FromSeconds(15),
    JobExpirationCheckInterval = TimeSpan.FromHours(1),
    CountersAggregateInterval = TimeSpan.FromMinutes(5),
    PrepareSchemaIfNecessary = true,
    DashboardJobListLimit = 50000,
    TransactionTimeout = TimeSpan.FromMinutes(1),
    TablePrefix = "_hangfire",
});

services.AddHangfire(op =>
{
    op.UseStorage(new MySqlStorage(Configuration["ConnectionStrings:DataProcessor"], options);
    op.UseTagsWithMysql(null, options);
});

```
