### ISSUE TITLE
upgrade Hangfire.MySqlStorage 2.0.3 Reference exception  

### ISSUE THREAD

**Issue by wenfeifei** [face-it/Hangfire.Tags#51]
upgrade Hangfire.MySqlStorage 2.0.3 Reference exception  
System.TypeLoadException: Could not load type 'MySql.Data.MySqlClient.MySqlConnection' from assembly 'MySqlConnector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92'.
   at Hangfire.Tags.MySql.MySqlTagsTransaction.ExpireSetValue(String key, String value, TimeSpan expireIn)

**Comment by wenfeifei** [comment]
Hangfire.MySqlStorage 2.0.2 Package MySQL connector 0.47.1 in is too low.You can upgrade to 2.0.3, where the referenced package MySQL connector version is 1.0.0

**Comment by erwin-faceit** [comment]
Apparently the interface of the MySQL Connector has changed between 0.47.1 and 1.0.0.0 version. The namespace changed, so I've updated as requested in order to maintain compatibility with newer versions.
