### ISSUE TITLE
Hangfire tags has huge memory food print in redis storage

### ISSUE THREAD

**Issue by kechf** [face-it/Hangfire.Tags#58]
Hi,
in our scenarios (we use the redis stroage) the tagged jobs has a high memory consumption, in comparison to the plain jobs without tags. The keys are also kept in redis for a long time. 
What is the reason for this?

For example:
In Redis storage the complete hangfire storage has a size of approx 30 MB and the "Tags" folder uses approx 20 MB of them.
![image](https://user-images.githubusercontent.com/23336242/207597187-e4f9224e-6e4b-4452-84c3-b07cbe2af19e.png)

**Comment by erwin-faceit** [comment]
Are you having a lot of deleted tasks? The current implementation has a bug where tags from deleted tasks are not removed. See #57 for more details.

Please let me know if that is the case here as well.

**Comment by kechf** [comment]
I think, this is our issue. Thanks!

**Comment by erwin-faceit** [comment]
Can you perhaps test the branch mentioned there?
