### ISSUE TITLE
How to retrieve jobs from hangfire with a given tag id?

### ISSUE THREAD

**Issue by scrawny-5** [face-it/Hangfire.Tags#59]
Does anyone know how can I retrieve jobs from Hangfire with a given tag id after using this extension? For instance, using a Where lambda expression or similar. I need to find out the status of all jobs with a certain tag.

(apologies in advance if this is not the right forum to ask)

**Comment by erwin-faceit** [comment]
You can try to use the same code as the monitoring pages are using?

https://github.com/face-it/Hangfire.Tags/blob/90e17f98fa2b7bcae39f1b6e128ba3e6c66c0bd6/src/Hangfire.Tags/Dashboard/Pages/TagsJobsPage.cshtml#L37-L56

Replace the variable Storage on line 37 with JobStorage.Current, and let me know how it goes.

**Comment by scrawny-5** [comment]
Thanks for the suggestion.

I can't seem to make use of the TagsStorage class as it's marked as internal.

**Comment by erwin-faceit** [comment]
You're absolutely right! Sorry about that. HangFire.Tags uses a mechanic where you're Razor cshtml page inherits ```TagsRazorPage```. From there you can get an instance of the ```ITagsServiceStorage``` interface, using the property ```TagContext.TagsServiceStorage```. 

The reason that's it this closed and difficult is the fact that you can have multiple dashboards on different url's, which makes the slug important when retrieving the correct ```ITagsServiceStorage```. 

So, I've added an extension method to the latest beta version (1.9.0-beta.2) of HangFire.Tags, which also requires an upgrade to HangFire 1.8.2. 

```c#
var tagstorage = JobStorage.Current.GetTagsMonitoringApi();
var matchingjobs = tagstorage.GetMatchingJobs(new[] { "tag1" }, 0, 10);
```

I hope this helps solving your problem. Sorry for leaving this issue open this long.
