### ISSUE TITLE
Question on Tag Amount Limits and Duplicate Tags

### ISSUE THREAD

**Issue by rob893** [face-it/Hangfire.Tags#75]
Just a question on if there is a limit to number of total tags. I know the search is a drop down but my use case has an upper limit of like 50k tags so I am wondering how this dropdown will react to that many tags.

Also, what happens when we add the same tag multiple times in a single job? I assume nothing but wanted to clarify.

**Comment by erwin-faceit** [comment]
The dropdown menu loads all tags when opening the page, so a big amount of tags might make this somewhat slower. The [Set] table has a pretty decent performance, one of our clients has 316k tags at the moment and there is no problem opening this page. If this becomes a problem, I might add an interface on the different storage implementations to load the tags dynamically when typing.

Adding the same tag is not a problem, they will be made unique, so only one will be added.

**Comment by rob893** [comment]
Perfect. Thanks for the fast response!
