### ISSUE TITLE
Tags expiration does not use Redis key prefix

### ISSUE THREAD

**Issue by jonathanschnabelwhatnot** [face-it/Hangfire.Tags#76]
Hi,

We configured Hangfire to use Redis for tags storage, and we have an issue where tags are not being expired.

This is how we configure Hangfire:

```
builder.Services.AddHangfire((sp,opts) =>
{
    var rs =  sp.GetService<IRedisService>();

    opts.UseRedisStorage(rs.data_apps_redis.Configuration, new Hangfire.Pro.Redis.RedisStorageOptions()
    {
        Prefix = $"hf:",
        MaxStateHistoryLength = 100,
        MaxSucceededListLength = EnvironmentStuff.is_development()?1000: 100000
    });
    opts.SetDataCompatibilityLevel(CompatibilityLevel.Version_170);
    opts.UseSimpleAssemblyNameTypeSerializer();
    opts.UseTagsWithRedis(new TagsOptions()
    {
        TagsListStyle = TagsListStyle.Dropdown
    });
    opts.UseConsole(new ConsoleOptions()
    {
        FollowJobRetentionPolicy = true,
        PollInterval = 5000
    });
});
```

The Redis key `hf:tags:expiry` contains values such as `tags:locktaken|d1d819eb-18f8-48cc-828b-decdc341032e`. When I look at the contents of the key `hf:tags:locktaken`, it contains values that should have been expired because the timestamp stored in `hf:tags:expiry` is several hours ago, and the expired tags watcher is supposed to run hourly.

I suspect that tags are not expired because is because keys in `hf:tags:expiry` does not contain the `hf:` prefix. Am I missing a configuration step?

We use the following versions:

- Hangfire: 1.7.34
- Hangfire.Pro: 2.3.2
- Hangfire.Pro.Redis: 2.8.20
- FaceIT.Hangfire.Tags.Pro.Redis: 1.9.1

Thanks for your help.

**Comment by erwin-faceit** [comment]
Could you try passing the RedisStorageOptions to the UseTagsWithRedis method as well? Like this:

```
builder.Services.AddHangfire((sp,opts) =>
{
    var rs =  sp.GetService<IRedisService>();

    var options = new Hangfire.Pro.Redis.RedisStorageOptions()
    {
        Prefix = $"hf:",
        MaxStateHistoryLength = 100,
        MaxSucceededListLength = EnvironmentStuff.is_development()?1000: 100000
    };

    opts.UseRedisStorage(rs.data_apps_redis.Configuration, options);
    opts.SetDataCompatibilityLevel(CompatibilityLevel.Version_170);
    opts.UseSimpleAssemblyNameTypeSerializer();
    opts.UseTagsWithRedis(new TagsOptions()
    {
        TagsListStyle = TagsListStyle.Dropdown
    }, options);
    opts.UseConsole(new ConsoleOptions()
    {
        FollowJobRetentionPolicy = true,
        PollInterval = 5000
    });
});
```

Also: apologies for my super late reply. I've been out of the running for the last few weeks, and before that too busy with work.
