### ISSUE TITLE
Hangfire.Redis.StackExchange

### ISSUE THREAD

**Issue by ltb27** [face-it/Hangfire.Tags#78]
Now Hangfire.Tags use Hangfire.Pro.Redis ,that is not free. Is there any other option for use [Hangfire.Redis.StackExchange](https://github.com/marcoCasamento/Hangfire.Redis.StackExchange)
 as a replace

**Comment by erwin-faceit** [comment]
Hangfire.Tags has implementations for both Redis versions of Hangfire. 

If you’ve updated Hangfire, make sure to switch to the preview version of Hangfire.Tags, which now has the prefix FaceIT (so it becomes FaceIT.Hangfire.Tags).

**Comment by erwin-faceit** [comment]
Please use https://www.nuget.org/packages/FaceIT.Hangfire.Tags.Redis.StackExchange/
