### ISSUE TITLE
RedisStorageOptions no longer defined in Hangfire.Redis.StackExchange

### ISSUE THREAD

**Issue by davidpipes** [face-it/Hangfire.Tags#79]
Updated Hangfire.Redis.StackExchange to 1.9.0 and I can't seem to get Tags to work with it. 

![image](https://github.com/face-it/Hangfire.Tags/assets/1081693/73aa1cfd-c4f8-4f5d-ab02-9fda17d8e30d)

Not sure if something changed or I am doing something wrong with the update. Trying to get tags working with redis.

**Comment by erwin-faceit** [comment]
I think you may need to update Hangfire.Tags to the preview version. Hangfire has made some really big changes, so it was hardly possible to maintain backwards compatible.

**Comment by erwin-faceit** [comment]
Forgot to add, Hangfire is prefixed now with FaceIT, because Hangfire registered the Hangfire prefix on Nuget.

**Comment by czimbortibor** [comment]
The preview version (at least 1.9.0-beta.4) doesn't seem to fix the namespace

**Comment by erwin-faceit** [comment]
Could you try to change Hangfire.Redis.StackExchange to version 1.9.2 or higher? Version 1.9.0 only supports netstandard 2.1, which might be incompatible with FaceIT.Hangfire.Tags.Redis.StackExchange. 

I've just tried this scenario locally, and both the core version as the .NET Framework version of the samples work as expected when referencing version 1.9.2 of Hangfire.Redis.StackExchange.

**Comment by r-win** [comment]
Since I didn't hear back, I assume this issue can be closed. Feel free to open a new issue if this is still a problem.
