### ISSUE TITLE
Missing Logs on UI when TAG is enabled 

### ISSUE THREAD

**Issue by maxiar** [face-it/Hangfire.Tags#88]
Hi! The Procesing results logs are missing when TAG is enabled..

I made some test, it's works success using hangfire without FaceIt.Tags but when I enabled Tags not work:

Only Hangfire...

<img width="935" alt="image" src="https://github.com/yuzd/Hangfire.HttpJob/assets/974115/556aa5be-9930-4b21-b223-ca7e6dd28e73">

Hnagifre + FaceIt.Tags...

<img width="946" alt="image" src="https://github.com/yuzd/Hangfire.HttpJob/assets/974115/44975eca-5af8-4484-8702-5a54199c8f91">

Any suggestion? Regards!

**Comment by erwin-faceit** [comment]
I suppose you’re using Hangfire.Console for that? We’re using that as well, together with Hangfire.Tags. Do you happen to have some javascript error in the console?

 Can you give me more information, like frameworks used, versions, perhaps configuration and setup code? It would be even better if you could recreate this issue in a fork of this code in the samples application(s).

**Comment by maxiar** [comment]
Fotgot it! I resolved! Simple Add this mising using, I'm an stupid! Sorry....

<img width="789" alt="image" src="https://github.com/yuzd/Hangfire.HttpJob/assets/974115/82bccfe0-3f57-4744-8a10-e7b2a33639a0">

**Comment by erwin-faceit** [comment]
Glad it worked out!
