### ISSUE TITLE
Unable to Search with Tags after Upgrading to Hangfire Version 1.8.12 and FaceIT.Hangfire.Tags.SqlServer to version 1.9.0-beta.3

### ISSUE THREAD

**Issue by YordiVanDyckIS** [face-it/Hangfire.Tags#89]
Description:

We recently upgraded our Hangfire version to 1.8.12 and FaceIT.Hangfire.Tags.SqlServer version to 1.9.0-beta.3 , and since then, we've encountered an issue with searching using tags. Previously, we were able to search efficiently with tags. However, after the upgrade, we're experiencing difficulties due to the large number of records containing tags.

Steps to Reproduce:

  1. Use FaceIT.Hangfire.Tags.SqlServer Version 1.9.0-beta.3
  2. Upgrade Hangfire to version 1.8.12.
  3. Attempt to search using tags.
  4.  Notice that the search functionality is not working as expected due to the large number of records containing tags.

Expected Behavior:

We expect the search functionality to work smoothly even with a large number of records containing tags, as it did before the upgrade.

Actual Behavior:

The search functionality is not working as expected after the upgrade to Hangfire version 1.8.12. It seems to struggle with handling the large number of records containing tags.

Additional Information:
    Screenshots:
![image](https://github.com/face-it/Hangfire.Tags/assets/141132672/919dadae-18bd-4759-bfa2-0fd28b42ac95)
![image](https://github.com/face-it/Hangfire.Tags/assets/141132672/46a047d9-5b00-4f77-9573-75b16023bcc0)

Any assistance or guidance on resolving this issue would be greatly appreciated.

**Comment by erwin-faceit** [comment]
Do you also know what the previous versions where? Of both Hangfire and Hangfire.Tags.

**Comment by YordiVanDyckIS** [comment]
For the tags version, we changed library form Hangfire.Tags.SqlServer version 1.8.2 to the FaceIT.Hangfire.Tags.SqlServer. The other one is deprecated and it recommended us to change to the FaceIT.Hangfire.Tags.SqlServer.

Our previous hangfire version was 1.7.12.

**Comment by erwin-faceit** [comment]
Ah, so that means that the Hangfire schema change since 1.8.2 could also be the source of this issue. I’ve encountered the same in our usage, but actually never related this to the schema change in Hangfire.

I’ll look into it!

**Comment by r-win** [comment]
Should be fixed in version 1.9.1 of SQL Storage
