### ISSUE TITLE
Support for Postgres and Sqlite?

### ISSUE THREAD

**Issue by Peter-Optiway** [face-it/Hangfire.Tags#9]
Any chance you could add support for Postgres and Sqlite?

Seems like a wonderful extension!

**Comment by yongliu-mdsol** [comment]
@Peter-Optiway 
We also find the need of adding Postgres support to Hangfire.Tags.
So we created one. 
Please find Postgres support in https://github.com/face-it/Hangfire.Tags/pull/14.

**Comment by Peter-Optiway** [comment]
@yongliu-mdsol Good job, lets hope this gets merged!

**Comment by erwin-faceit** [comment]
I've just merged and pushed the PostgreSql addition. Thank you very much, @yongliu-mdsol! Awesome job.

**Comment by erwin-faceit** [comment]
And I've also added an SQLite version: https://www.nuget.org/packages/Hangfire.Tags.SQLite
