### ISSUE TITLE
Provide access to JobStorage.RemoveTags

### ISSUE THREAD

**Issue by robin-83** [face-it/Hangfire.Tags#90]
Hello,
although the Interface IJobStorage is public, I dont see any way to create a concrete implementation for usage in my Hangfire project. Internally in Hangfire.Tags a new instance is created whenever needed but this cannot be done as a consumer of the package. 
The public HangfireExtensions unfortunately does not contain any RemoveTags methods.
However I see this as a useful enhancement and would be glad if this can be added to the official package. Currently we duplicated your code from TagStorage and call RemoveFromSet directly.
Thanks for your great work so far!
Robin

**Comment by erwin-faceit** [comment]
Instead of making TagStorage public, how about an extension method just like AddTags?

**Comment by robin-83** [comment]
Sure, this would work perfectly for me.

**Comment by r-win** [comment]
Available from FaceIT.Hangfire.Tags version 1.9.0-beta.5 or version 1.9.0
