### ISSUE TITLE
Wrong dapper version in dependencies?

### ISSUE THREAD

**Issue by papusa** [face-it/Hangfire.Tags#94]
Hi,
Latest `FaceIT.Hangfire.Tags.SqlServer` is requiring not available  dapper version.
![image](https://github.com/user-attachments/assets/4d57e9f8-b244-488f-a6c1-06dd049228d3)
Latest available version for dapper is `2.1.35`.
![image](https://github.com/user-attachments/assets/fd4f0254-cd1c-403f-95bf-4d62f7b184ca)
Looks like version `2.1.44` is unlisted by dapper team.
https://github.com/DapperLib/Dapper/issues/2096

Thanks.

**Comment by r-win** [comment]
Nice. That's the reason why you don't just pull packages. On the other hand, Hangfire.Tags doesn't need the latest version, so that's why I shouldn't use 2.* versions in project files.

Lesson learned, I'll downgrade it to 2.0.4.
