### ISSUE TITLE
FaceIT.Hangfire.Tags.SqlServer breaks with Hangfire.SqlServer 1.8.15

### ISSUE THREAD

**Issue by AlexMedia** [face-it/Hangfire.Tags#97]
After upgrading Hangfire.SqlServer to version 1.8.15, this package no longer works. The following error gets logged when trying to execute a task:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hangfire.Tags.SqlServer.SqlTagsTransaction..ctor(SqlServerStorageOptions options, IWriteOnlyTransaction transaction)
   at Hangfire.Tags.SqlServer.SqlTagsServiceStorage.GetTransaction(IWriteOnlyTransaction transaction)
   at Hangfire.Tags.Storage.TagExpirationTransaction.Persist(String jobid)
   at Hangfire.Tags.States.TagsCleanupStateFilter.OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
   at Hangfire.States.StateMachine.InvokeOnStateApplied(KeyValuePair`2 x) in C:\projects\hangfire-525\src\Hangfire.Core\States\StateMachine.cs:line 116
```

The root cause lies in this bit of reflection: https://github.com/face-it/Hangfire.Tags/blob/5038a69e3a8496168320590fd22fc8789c5de791/src/FaceIT.Hangfire.Tags.SqlServer/SqlTagsTransaction.cs#L71-L77 as it tries to get the `SqlCommandBatchParameter` type, which [no longer exists in Hangfire.SqlServer 1.8.15](https://github.com/HangfireIO/Hangfire/compare/v1.8.14...v1.8.15#diff-ee8d9347dac19fe171e291d61cf331c7b7eead9b9d970147a8dd34d0add24636L127-L153).

**Comment by smadep** [comment]
facing same problem ...

**Comment by HernJer** [comment]
Has this gotten any attention?

**Comment by erwin-faceit** [comment]
I haven’t had the time yet, unfortunately, but it’s high om the list!

**Comment by hiblen** [comment]
I have the same issue, so following in interest

**Comment by aldrashan** [comment]
Same problem here

**Comment by blinkwiese** [comment]
+1

**Comment by ttkoma** [comment]
+1

**Comment by hinerasky** [comment]
+1

**Comment by erwin-faceit** [comment]
Can you try this beta package? Let me know if it works, so I can publish a stable version instead:

https://www.nuget.org/packages/FaceIT.Hangfire.Tags.SqlServer/1.9.15-beta.1 (if the package is not visible yet, it'll be within the hour!)

**Comment by alvicode** [comment]
> Can you try this beta package? Let me know if it works, so I can publish a stable version instead:
> 
> https://www.nuget.org/packages/FaceIT.Hangfire.Tags.SqlServer/1.9.15-beta.1 (if the package is not visible yet, it'll be within the hour!)

For me the exception is gone. I would say it works. Will deploy to the dev environment and give further feedback.

**Comment by alvicode** [comment]
Works well for me with Hangfire.SqlServer 1.8.17.

Thanks for the effort.

**Comment by HernJer** [comment]
Looks good. Thanks!
