### ISSUE TITLE
Redis tags dont work

### ISSUE THREAD

**Issue by sunnyzees** [face-it/Hangfire.Tags#98]
When I try to use redis pro tags , the batch jobs fails wirh error specifying queue names is not supported while.enqueing job use queue attribute instead.

**Comment by erwin-faceit** [comment]
Do you happen to have sample code for this issue? I don't need a full project, just the invocation and attributes on the classes should be enough. 

As it's currently described, this issue is not clear to me yet, so I need more information.

**Comment by erwin-faceit** [comment]
No response in 3 weeks. Closing this issue.

On a side note: if you're enqueing jobs and specifying the queuename in the BackgroundJob.Enqueue method, that is obsolete now. Please change to attributes only.
